homeassistant:
  name: Farm Segulja
  latitude: 31.430417
  longitude: -95.379194
  elevation: 0
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
config:
http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

updater:
discovery:
conversation:
history:
logbook:
map:
sun:

mqtt:

### DEVICE TRACKERS ###
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.254.0/24
    home_interval: 3

### INPUT SELECTS ###
input_select:
  house_mode:
    name: House Mode
    options:
      - Morning
      - Day
      - Evening
      - Night
      - Bedtime
  presence:
    name: Presence
    options:
      - Home
      - Away

### SENSORS ###
sensor:
  - platform: darksky
    api_key: afa34bc609b9663a088f2f877096ca2b
    monitored_conditions:
      - summary
      - icon
      - temperature
      - humidity
      - temperature_max
      - temperature_min
      - wind_speed
    units: us
    update_interval: 00:30:00

weather:
  - platform: darksky
    api_key: afa34bc609b9663a088f2f877096ca2b

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

zwave:
  usb_path: /dev/ttyACM0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
